plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
    id "kotlin-kapt"
}

apply from: "$project.rootDir/versions.gradle"

android {
    namespace 'ru.ansmos.filmoteka'
    compileSdk 32

    buildFeatures{
        viewBinding true
        dataBinding true
    }

    defaultConfig {
        applicationId "ru.ansmos.filmoteka"
        minSdk 29
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    flavorDimensions "version"

    productFlavors {
        pro {
            dimension "version"
            applicationIdSuffix ".pro"
            versionNameSuffix "-pro"
        }
        free {
            dimension "version"
            applicationIdSuffix ".free"
            versionNameSuffix "-free"
        }
    }
    sourceSets {
        pro {
            java {
                srcDirs 'src\\pro\\java'
            }
        }
        free {
            java {
                srcDirs 'src\\free\\java'
            }
        }
    }

}

dependencies {

    implementation project(path: ':net_tmdb')
    implementation project(path: ':db_module')

    def lifecycle_version = "2.4.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"

    implementation 'androidx.core:core-ktx:1.8.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'

    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    //Glide
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    //Lottie
    implementation 'com.airbnb.android:lottie:3.4.4'
    //Gson
    implementation 'com.google.code.gson:gson:2.8.6'
    //Dagger
    implementation dagger
    kapt daggerCompiler

    //Room
    def room_version = "2.4.0"
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-rxjava3:$room_version" //RxJava
    kapt "androidx.room:room-compiler:$room_version"

    //implementation paging
    implementation pagingRuntime
    implementation pagingRxJava

    //RxJava
    implementation rxJava
    implementation "io.reactivex.rxjava3:rxandroid:$rxJavaVersion"
    implementation "io.reactivex.rxjava3:rxkotlin:$rxJavaVersion"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}